# Generated by Django 3.2.16 on 2022-10-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='url_or_message',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
