# Generated by Django 3.2.16 on 2022-10-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0002_add_url_or_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qrcode_images',
            field=models.FileField(null=True, upload_to='qrcode_images/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='url_or_message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
